POST http://localhost:3000/api/todos/create HTTP/1.1
content-type: application/json




{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET http://localhost:3000/api/todos  HTTP/1.1

###
DELETE  http://localhost:3000/api/todos/delete/2

###
PUT http://localhost:3000/api/todos/update/3 HTTP/1.1
content-type: application/json

{
    "title": "saasfasf",
    "description": "Wed, 21 asfasfasfa 2015 18:27:50 GMT"
}
###
PUT http://localhost:3000/api/todos/updatefav/2 HTTP/1.1
content-type: application/json
  
    {
        "fav" : "false" 
    }